name: Continuous Integration
on:
  pull_request:
    branches:
    - main
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: go
      name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test
      name: Go Tests
      run: |
        go test -coverprofile=coverage.out ./...
    - id: lint
      name: Go Lint
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: './...'
        