name: Release
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: go
      name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: test
      name: Go Tests
      run: |
        go test -coverprofile=coverage.out ./...
    - id: version
      uses: paulhatch/semantic-version@v4.0.3
    - id: docker-build
      name: Build Docker Image
      run: |
        docker build \
            -t marcboudreau/hvc:${{ steps.version.outputs.version }} \
            -t marcboudreau/hvc:${{ steps.version.outputs.major }} \
            -t marcboudreau/hvc:latest \
            .
    - id: docker-login
      name: Docker Hub Login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        PASSWORD: ${{ secrets.DOCKERHUBPASSWORD }}
    - id: docker-push
      name: Docker Push
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.version.outputs.version }}
    - id: tag
      name: Tag Repository
      run: |
        git tag v${{ steps.version.outputs.version }}
        git push --tags
